### PR TITLE
Plus Jakarta Sans Cyrillic

### PR DESCRIPTION
**Pull request by ravid-dubsteper**
After a year i finally made basic cyrillic for the typeface.
Also for the typeface was created bulgarian localisation with help of @StefanPeev

Unfortunately there's no extended support of cyrillic for now (except of mongolian alphabet especially made for @Uranbold :D ).
And the cyrillics doesn't have kerning (except ukainian symbols "і ї") and OpenType alternates for ss01, ss02 and ss03

image

### CODE REVIEW

**Comment by Uranbold** [comment]
Thank you, brother :)

**Comment by Uranbold** [comment]
@emmamarichal Please review it. Thanks.

**Comment by emmamarichal** [comment]
Hello @ravid-dubsteper,

Thanks a lot for your contribution, we appreciate it!
I took a look to the files, it's ok to don't have a huge langage support. Your work covers the Google Font Cyrillic Core glyphset, it's enough for us :)

The thing here, is that there are no italics, and unfortunately, we can't onboard the update without them. The glyphset has to be the same in upright and italic.
Do you plan to draw them? You can easily generate them, thanks to some Glyphs tools or RMX tool. Please don't hesitate if you need any help or advices about it.

Cheers!
Emma

**Comment by ravid-dubsteper** [comment]
hi @emmamarichal
thank you for the comment

i have a question. if the language set should be in the both styles, in this case is roman and italics, then why you published WIX madefor text typeface?🙃 as you can see on the screenshot, there's no cyrillic in the italics.
image

**Comment by ravid-dubsteper** [comment]
@emmamarichal

about italics, I'm afraid them:))
i never did italics.

i use fontlab 8 and, i don't know, RMX supports new fontlab or not

**Comment by Uranbold** [comment]
Can you accept the PR?

**Comment by emmamarichal** [comment]
I'll discuss about it with the team today. I'll let you know, thanks for your patience

**Comment by davelab6** [comment]
@twardoch may be able to advise on how to make quick obliques with Fontlab

**Comment by Uranbold** [comment]
Any news guys?

**Pull request merged**
